# Generated by Django 5.0.1 on 2024-01-28 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_post_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
    ]
